### ISSUE TITLE
Can not access Facebook

### ISSUE THREAD

**Issue by vdhong** [TechnikEmpire/CitadelCore#63] opened 2018-09-11 08:57 UTC
Hello again,
My app use CitadelCore to log URL user accessed, it worked ok (facebook also ok) on my PC but on my friend's PC he can not access facebook, I see Chrome show "failed" on "inspect > network" and so much warning in my app "WARN: Skipping imposter packet.  WindowsDiverter.cs::RunDiversion() #338", it does not have any error. I see almost css, js link of facebook failed in "inspect > network" of Chrome.
He can access other web.
This issue happens after I update CitadelCore.Windows.
Any idea?

**Comment by TechnikEmpire** [comment] 2018-09-11 09:16
@vdhong A flood of errors about imposter packets. hmmm. Is your friend running an antivirus software that performs HTTP/HTTPS inspection?

**Comment by TechnikEmpire** [comment] 2018-09-11 09:26
@vdhong Please follow up on the .Windows version of the repo here:

https://github.com/TechnikEmpire/CitadelCore.Windows/issues/13

**Comment by TechnikEmpire** [comment] 2018-09-11 09:35
@vdhong I just pushed a new release of CitadelCore.Windows, let me know if that fixes your issue on the bug thread I linked to above.

**Comment by vdhong** [comment] 2018-09-11 09:53
Thank you, I will let you know.

**Comment by TechnikEmpire** [comment] 2018-09-12 03:51
@vdhong did that resolve your issue?

**Comment by vdhong** [comment] 2018-09-13 06:29
@TechnikEmpire Yes, issue solved. Thank you!

**Comment by vdhong** [comment] 2018-09-13 06:33
But now, I have another issue: I can send message on facebook but I can not receive message other send me. It's mean my friend can receive my message but I can not receive his message send me because my PC is running my app. 
I check console of browser and see error: 
`WebSocket connection to 'wss://edge-chat.facebook.com/chat?region=ash' failed: Error during WebSocket handshake: Unexpected response code: 200`
I think CitaldelCore changed response code of this packet or this is not http package.

**Comment by vdhong** [comment] 2018-09-13 06:43
More details about issue above:
Request header:
```
GET wss://edge-chat.facebook.com/chat?region=ash HTTP/1.1
Host: edge-chat.facebook.com
Connection: Upgrade
Pragma: no-cache
Cache-Control: no-cache
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/68.0.3440.106 Safari/537.36
Upgrade: websocket
Origin: https://www.facebook.com
Sec-WebSocket-Version: 13
Accept-Encoding: gzip, deflate, br
Accept-Language: en-US,en;q=0.9,vi;q=0.8
Cookie: ...
Sec-WebSocket-Key: ...
Sec-WebSocket-Extensions: permessage-deflate; client_max_window_bits
```


Response header:
```
HTTP/1.1 200 OK
Connection: close
Date: Thu, 13 Sep 2018 06:29:49 GMT
Server: Kestrel
Content-Length: 0
```

**Comment by TechnikEmpire** [comment] 2018-09-14 13:08
@vdhong Ok, use this bug ticket instead for your new issue:

https://github.com/TechnikEmpire/CitadelCore/issues/58

**Comment by TechnikEmpire** [comment] 2018-09-14 13:59
Actually I just tested this and it's working fine with the bundled example application. Check your filtering rules because you're probably dropping the websocket connection.

**Comment by vdhong** [comment] 2018-09-15 01:55
@TechnikEmpire I sure my filtering rules do not drop any websocket, I just filter to drop some domain. That issue happened yesterday but not today, I do not change anything in my app but now facebook chat can work normal and no error showed in console log.

**Comment by leminhthanh1998** [comment] 2018-10-07 01:08
@TechnikEmpire When I run Example project and I have the same problem as vdhong.
In the console of Chrome see error: WebSocket connection to 'wss://edge-chat.facebook.com/chat?region=atn' failed: Error during WebSocket handshake: Unexpected response code: 200

**Comment by TechnikEmpire** [comment] 2018-10-07 01:52
Ok I'll look into it. But is it actually causing the chat to break? Because I tried chat with the filter on and it worked, and then the other user reported that the issue was gone. You're running the latest version of the engine?

**Comment by leminhthanh1998** [comment] 2018-10-07 02:27
@TechnikEmpire Yes,I run the latest. CitadelCore 3.0.14 and CitadelCore.Windows 3.0.16

**Comment by vdhong** [comment] 2018-10-07 03:55
I think this is unstable issue because sometime it happens sometime it does not.

**Comment by leminhthanh1998** [comment] 2018-10-07 07:42
@vdhong I got stuck on this problem since yesterday :3

**Comment by TechnikEmpire** [comment] 2018-10-07 12:09
My house is undergoing some pretty big repairs so I'm in a hotel for a bit guys, I won't be able to address this for a few days. Will as soon as I get back though because I have commercial software relying on this.

**Comment by TechnikEmpire** [comment] 2018-10-07 12:11
For my own records, I think this would be caused by setting the default response handler to 200 in the http handler, which would get this first before an Upgrade handshake. Then somehow in the logic gates following, a certain condition causes this default value not to get changed.

**Comment by leminhthanh1998** [comment] 2018-10-15 12:37
And now it is working fine, don't have any error with facebook chat!

**Comment by TechnikEmpire** [comment] 2018-10-15 19:32
That's weird. I'm working my way around to this issue. If I can't reproduce though, I'll have to close it out.

**Comment by TechnikEmpire** [comment] 2018-10-16 02:32
I looked over the code guys and I can't see where the engine would be causing this. Response status code is set, always, to precisely what the upstream server is responding. The 200 message coming from Kestrel would indicate that the connection has fallen through the tumblers and escaped the logic for handling even still, I can't see how. The code is set immediately.

**Comment by TechnikEmpire** [comment] 2018-10-16 02:51
This might possibly be caused by https://www.nuget.org/packages/System.Net.WebSockets.Client.Managed/

This package is used because Microsoft is dumb and they purposely hold back websocket support on Windows 7 I guess to strong arm people into upgrading windows. This package is fully managed, written by Microsoft, but they still have refused to resolve this issue. Their "solution" was to make it only work in .NET Core 2.1, but not full.

Anyway that package had some bugs that were patched recently. That's all I can figure, is that these connections were dying, the engine was handling the error and then returning from the failure, which would give a 200 response.

**Comment by TechnikEmpire** [comment] 2018-10-17 04:52
I'm publishing a new release tonight, so you guys should give it a try and see if the problem was the websocket library.

**Comment by leminhthanh1998** [comment] 2018-10-17 09:57
@TechnikEmpire This error happen againt, now I can't receive any message.
![error](https://user-images.githubusercontent.com/21048628/47078563-c37e5d80-d22d-11e8-8ec7-f57bb8012573.png)

**Comment by TechnikEmpire** [comment] 2018-10-17 16:05
@leminhthanh1998 And you're sure this is with version 3.1.2? Thanks for checking this out for me.

**Comment by TechnikEmpire** [comment] 2018-10-17 22:35
I guess I'll have to actually break out the debugger if you're still seeing this 3.1.2. I don't use Facebook so I'll have a hard time reproducing.

**Closed** 2018-11-09 15:41 UTC
Labels: bug, external

**Comment by TechnikEmpire** [comment] 2018-11-09 16:54
@vdhong And @leminhthanh1998 This issue is now fixed.
